[package]
name = "aerugo"
version = "0.1.0"
authors = ["FaneTheEternal <artemyev.vova@gmail.com>"]
edition = "2021"

[[bin]]
name = "game"
src = "src/game/bin/main.rs"

[dependencies]
bevy = "0.6"
serde = "1.0.134"
