[package]
name = "aerugo"
version = "0.1.0"
authors = ["FaneTheEternal <artemyev.vova@gmail.com>"]
edition = "2018"

[dependencies]
#futures = "0.3"
tiny-skia = "0.5.1"
usvg = "0.15.0"
resvg = "0.15.0"
itertools = "0.10.1"

[dependencies.sdl2]
version = "0.34.3"
default-features = false
features = ["ttf", "image"]

[dependencies.uuid]
version = "0.8.2"
default-features = true
features = ["v4"]
