[package]
name = "aerugo"
version = "0.1.0"
authors = ["FaneTheEternal <artemyev.vova@gmail.com>"]
edition = "2021"

[[bin]]
name = "game"

[[bin]]
name = "editor"

[dependencies]
bevy = "0.6"
bevy_egui = "0.10"

serde = "1.0.134"
serde_json = "1.0"

uuid = { version = "0.8", features = ["serde", "v4"] }
