[package]
name = "aerugo"
version = "0.1.0"
authors = ["FaneTheEternal <artemyev.vova@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.sdl2]
version = "0.34.3"
default-features = false
features = ["ttf", "image"]
